# Generated by Django 5.1.5 on 2025-01-29 10:14

import uuid

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Country",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "uuid",
                    models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
                ),
                ("name", models.CharField(max_length=100)),
                ("search_text", models.CharField(max_length=100)),
                ("search_count", models.IntegerField()),
                ("code", models.CharField(max_length=2)),
                ("phone_code", models.CharField(max_length=5)),
                (
                    "is_deleted",
                    models.BooleanField(
                        choices=[("False", "Active"), ("True", "Deleted")],
                        default=False,
                        verbose_name="Is Deleted",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Created At"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Updated At"),
                ),
            ],
            options={
                "verbose_name": "Country",
                "verbose_name_plural": "Countries",
                "db_table": "country",
                "ordering": ["-id"],
            },
        ),
        migrations.CreateModel(
            name="City",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "uuid",
                    models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
                ),
                ("name", models.CharField(max_length=100)),
                ("search_text", models.CharField(max_length=100)),
                ("search_count", models.IntegerField()),
                (
                    "is_deleted",
                    models.BooleanField(
                        choices=[("False", "Active"), ("True", "Deleted")],
                        default=False,
                        verbose_name="Is Deleted",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Created At"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Updated At"),
                ),
                (
                    "country",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="cities",
                        to="location.country",
                        verbose_name="Country",
                    ),
                ),
            ],
            options={
                "verbose_name": "City",
                "verbose_name_plural": "Cities",
                "db_table": "city",
                "ordering": ["-id"],
            },
        ),
        migrations.CreateModel(
            name="Airport",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "uuid",
                    models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
                ),
                ("name", models.CharField(max_length=100)),
                ("search_text", models.CharField(max_length=100)),
                ("search_count", models.IntegerField()),
                ("code", models.CharField(max_length=2)),
                (
                    "is_deleted",
                    models.BooleanField(
                        choices=[("False", "Active"), ("True", "Deleted")],
                        default=False,
                        verbose_name="Is Deleted",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Created At"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Updated At"),
                ),
                (
                    "city",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="airports",
                        to="location.city",
                        verbose_name="City",
                    ),
                ),
                (
                    "country",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="airports",
                        to="location.country",
                        verbose_name="Country",
                    ),
                ),
            ],
            options={
                "verbose_name": "Airport",
                "verbose_name_plural": "Airports",
                "db_table": "airport",
                "ordering": ["-id"],
            },
        ),
    ]
