# Generated by Django 5.1.5 on 2025-01-29 09:45

import json

from django.conf import settings
from django.db import migrations, transaction
from django.db.backends.sqlite3.schema import DatabaseSchemaEditor
from django.db.migrations.state import StateApps


def set_fixtures(apps: StateApps, schema_editor: DatabaseSchemaEditor) -> None:
    """
    * Set initial data from fixtures folder
    """

    city_model = apps.get_model("location", "City")
    country_model = apps.get_model("location", "Country")
    airport_model = apps.get_model("location", "Airport")

    base_dir = settings.BASE_DIR

    with transaction.atomic():
        with open(base_dir / "location/fixtures/countries.json", "r") as file:
            countries = file.read()
            data = json.loads(countries)

            country_list = [country_model(search_count=0, **item) for item in data]
            country_model.objects.bulk_create(country_list)

        with open(base_dir / "location/fixtures/cities.json", "r") as file:
            cities = file.read()
            data = json.loads(cities)

            for item in data:
                country = country_model.objects.get(code=item["country_code"])
                city, e = city_model.objects.get_or_create(
                    search_count=0, country=country, name=item["name"]
                )
                airtports = item["airports"]
                for airport in airtports:
                    airport_model.objects.get_or_create(
                        search_count=0,
                        city=city,
                        country=country,
                        name=airport["name"],
                        code=airport["code"],
                    )


class Migration(migrations.Migration):

    dependencies = [
        ("location", "0001_initial"),
    ]

    operations = [
        migrations.RunPython(set_fixtures),
    ]
